name: theme_weaver_generator
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  build: ^3.0.2
  analyzer: ^7.7.1
  source_gen: ^3.1.0
  crypto: ^3.0.6
  glob: ^2.1.3
  path: ^1.9.1
  code_builder: ^4.10.1
  dart_style: ^3.1.1
  collection: ^1.19.1
  theme_weaver: ^0.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.6
